-- add_includedirs("./include/amxmodx/public")
add_includedirs("./include/hlsdk-2.3-p4/multiplayer/engine")
add_includedirs("./include/hlsdk-2.3-p4/multiplayer/common")
add_includedirs("./include/hlsdk-2.3-p4/multiplayer/pm_shared")
add_includedirs("./include/hlsdk-2.3-p4/multiplayer/dlls")
add_includedirs("./include/metamod")

-- add_includedirs("../../sdk/hlsdk-2.3-p4/multiplayer/engine")
-- add_includedirs("../../sdk/hlsdk-2.3-p4/multiplayer/common")
-- add_includedirs("../../sdk/hlsdk-2.3-p4/multiplayer/pm_shared")
-- add_includedirs("../../sdk/hlsdk-2.3-p4/multiplayer/dlls")
-- add_includedirs("../../sdk/metamod-1.20/metamod")

target("demobot")
    set_kind("shared")
    set_symbols("debug")
    add_files("src/demobot/*.cc")
    -- add_cxxflags("-D_GLIBCXX_USE_CXX11_ABI=0")
    -- add_includedirs("src/demo/")
    set_prefixname("")
    -- set_suffixname("_mm_$(arch)")
    after_build(function(target)
        os.cp(target:targetfile(), "$(projectdir)/bin")
    end)
target("demoparser")
    set_kind("binary")
    set_symbols("debug")
    add_files("src/parser/parser.cc")
    after_build(function(target)
        os.cp(target:targetfile(), "$(projectdir)/bin")
    end)